#!/usr/bin/env bash
# Bring up the whole local dev stack: infra, schema, Zitadel, seed data.
#
# The cold-start sequence docs/dev-signing-in.md documents as seven separate
# commands, as one. Every step here is independently idempotent (seed.sh and
# zitadel-configure.sh say so in their own header comments; EF Core migrations
# no-op on an up-to-date schema; `docker compose up -d` no-ops on running
# containers), so this is safe to run before every "Full Stack" launch, not
# only on a cold machine.
#
# Usage: scripts/dev-stack-up.sh
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

docker compose -f deploy/compose.dev.yml --profile core up -d
deploy/seed/seed.sh
scripts/dev-migrate.sh
deploy/seed/zitadel-configure.sh
deploy/seed/seed.sh   # second pass: the schema exists now, seeds tenants + identity_provider

# Nothing else keeps apps/web/.env.local in sync with the OIDC client id
# zitadel-configure.sh just (re)generated - docs/dev-signing-in.md documents
# this as a manual step ("copy the new client id across"). Do it here so a
# fresh or recreated Zitadel volume doesn't silently break the web app.
oidc_env="deploy/.zitadel/oidc.generated.env"
if [ -f "$oidc_env" ]; then
  # shellcheck disable=SC1090
  . "$oidc_env"
  cat > apps/web/.env.local <<EOF
# Generated by scripts/dev-stack-up.sh. Do not edit; re-run instead.
VITE_OIDC_ISSUER=${NIX_OIDC_ISSUER}
VITE_OIDC_CLIENT_ID=${NIX_OIDC_CLIENT_ID}
VITE_WORKSPACE_ID=a1000000-0000-4000-8000-000000000001
EOF
  echo "dev-stack-up: wrote apps/web/.env.local"
fi
